name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: 'acf-barcodescanner'
      FILES_TO_INCLUDE: 'composer.json composer.lock LICENSE acf-barcodescanner.php lang build fields'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.0.0

      # Install dependencies
      - name: Install dependencies
        run: npm ci --ignore-scripts --legacy-peer-deps

      # Build the plugin
      - name: Build plugin
        run: |
          npm run build

      # Zip the files
      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          tar -czf "${GITHUB_SHA}".tar.gz --ignore-failed-read ${FILES_TO_INCLUDE}

      # Upload the artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-build
          path: ${{ github.sha }}.tar.gz
          retention-days: 1
